# Generated by Django 4.0.6 on 2022-08-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0002_genre_description_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zine',
            name='name',
            field=models.CharField(default='DefunctZine', max_length=100),
            preserve_default=False,
        ),
    ]
